### ISSUE TITLE
_USE_MATH_DEFINES gets removed

### ISSUE THREAD

**Issue by Predelnik** [slycelote/caide#12]
After a bit of playing around I've found the following workaround (just to use macro in next line):

       #define _USE_MATH_DEFINES
       _USE_MATH_DEFINES

While workaround is not actually that bad, it may still be unobvious.  So probably it's at least advisable to add it to readme or maybe fix it other way if it is possible.

**Comment by slycelote** [comment]
Right, unused macro definitions get removed, but sometimes it's undesirable. There is already parameter `keep_macros` that avoids collapsing this:

```c++
#ifdef _WIN32
//windows specific
#else
//other
#endif
```

into

```c++
// windows specific
```

I'm going to make it work for your scenario too.

**Comment by slycelote** [comment]
This will be fixed in the next release.
