### ISSUE TITLE
Caide window is inactive if Visual Studio is launched by double clicking a caide solution

### ISSUE THREAD

**Issue by slycelote** [slycelote/caide#13]
A workaround is to close the solution from the File menu and then open it again from File -> Recent solutions

**Comment by MiracleEEEE** [comment]
Something wrong...I create a cmake project, and I press "create caide solution",but..
![image](https://user-images.githubusercontent.com/26194256/39248951-0f6dda96-48d0-11e8-95aa-d414b730d99c.png)
 the file is produced,(.caide, cpplib, include, templates).
I'm running caide on Visual Studio 2017.

**Comment by slycelote** [comment]
@MiracleEEEE Can you check if output window of Visual Studio contains any error messages? You should be able to activate it with `Ctrl+Alt+O` or from View menu.

**Comment by MiracleEEEE** [comment]
I create a new solution project and all is well. Just it cant run well on cmake project..

**Comment by slycelote** [comment]
@MiracleEEEE Glad it works for you! I missed cmake in your first message, yes you're supposed to create a new caide solution in an empty directory. (VsCaide was originally released for VS 2013, which didn't even support cmake projects.)

Anyway, it's unrelated to this issue which remains open.

**Comment by vpyvovar** [comment]
I have this situation frequently. Especially it can happen after VS crash and re-opens. After that vscaide remains inactive and button doe snot work, so you cant even switch problems.
Workaround I found is to uninstall and install vscaide. After installation it will promt to allow access to internet to this application, and when you click "yes" everything comes back.

Of course crash in the middle of contest of VS is unacceptable. It's about 5-10 min to uninstall and install back

**Comment by slycelote** [comment]
Hmm, which issue are we talking about right now? If it's the issue in the title, then you don't have to reinstall VsCaide, you can use the workaround in the first post, or launch Visual Studio from start menu / desktop shortcut and open the solution from recent files menu.

If you experience crashes due to VsCaide, then do you have reproduction steps?

You can also try the development build [here](https://github.com/slycelote/caide/releases/tag/v2.4.2-pre), it should fix this issue and a few others.
