### ISSUE TITLE
How can I remove a problem?

### ISSUE THREAD

**Issue by MiracleEEEE** [slycelote/caide#15]

**Comment by slycelote** [comment]
If you use VsCaide extension, either remove the project corresponding to the problem, or click Archive button to remove currently active problem. (This will actually move the problem to archive directory, but you can simply clear the directory if you're worried about disk space.)

If you use the command line utility, simply remove the problem's directory to remove it completely, or use `caide archive` command to move it to the archive.

**Comment by MiracleEEEE** [comment]
thx
