### ISSUE TITLE
Support C++17

### ISSUE THREAD

**Issue by codereport** [slycelote/caide#19]
Can't figure out how to support C++14 and C++17. I have changed the ISO standard to C++17 for each of the projects:

- cf####A
- cpplib
- submission

But I still get an error on the concat.cpp file. Maybe there is a way to do it but can't figure it out.

**Comment by codereport** [comment]
Update: looks like there is support for C++14 which is awesome. You just need to update the caide.ini file. But C++17 still is missing.

**Comment by slycelote** [comment]
Yeah, caide.ini needs to use a clang option for C++ standard, e.g. `-std=c++14`. C++17 should already be supported in master branch, I just need to take some time and publish a release...

**Comment by codereport** [comment]
Expect a spike in usage: https://youtu.be/qNKBdqifxpU 
Eagerly awaiting C++17, let me know if there is anything I can do to help :)

**Comment by slycelote** [comment]
I published a release on github, C++17 support is now available with `-std=c++1z`. I'll publish the new version of the extension in Visual Studio marketplace some time later.

**Comment by codereport** [comment]
Awesome, I will mention in my video tonight! Thanks!

Conor
________________________________
