### ISSUE TITLE
I cannot find any C# README. 

### ISSUE THREAD

**Issue by SilentHG** [slycelote/caide#25]
it would be really helpful, if their was a README for c#.

I am currently using VS2019, Extension is working fine for me, on default it is creating c++ files, but you can change language.

**Comment by slycelote** [comment]
VS2019 is currently unsupported (I'm surprised it works for you). In earlier versions, you can edit caide.ini as described [here](https://github.com/slycelote/caide/tree/release/libcaide#core-section) to set the default programming language, or change it on the fly via the combobox.

**Comment by slycelote** [comment]
Closing this for now. Let me know if you need any further help.
