### ISSUE TITLE
Caide for docker

### ISSUE THREAD

**Issue by mfornet** [slycelote/caide#26]
Caide have been an extremely helpful tool for me, primarily its ability to create single file ready to submit that uses code from library headers. It has been hard to use it on different platforms, since compiling is not easy/fast, but we have binary released. The workaround I found was using docker to run such binaries. The result was this docker wrapper which I wanted to share: https://github.com/mfornet/caide-docker

**Comment by slycelote** [comment]
Thanks @mfornet. I publish statically linked executables for windows and Linux, so those should be easy to use. However, I don't have access to a MacOS machine, so the docker image could be a useful workaround.
If you're primarily interested in C++ code inliner, take a look at https://github.com/slycelote/caide-cpp-inliner, it's a library that's used by caide and published as a separate repo. It also contains a simple command-line executable that can be run to inline the code. I don't publish binaries for it, but it's easier to build (only cmake/c++ compiler and possibly some clang dependencies are required).
