### ISSUE TITLE
Unable to parse the problem from Codechef.

### ISSUE THREAD

**Issue by lazyboson** [slycelote/caide#28]
I have tried to parse the problem from the codechef with the following link.
https://www.codechef.com/problems/LIFTME
it fails to parse with the following error
![Annotation 2020-04-27 160901](https://user-images.githubusercontent.com/63603603/80363412-d00f5780-88a1-11ea-975c-4d3004b68891.png)

the competitive companion doesn't work as well on my PC. I am at windows 10 and with visual studio 19 (community edition).

**Comment by slycelote** [comment]
I'll look into it. What is the issue with Competitive Companion? You might need to change the port in Competitive Companion settings, VsCaide port is currently 8080.
You could also try CHelper browser extension, maybe it will work better.

**Comment by lazyboson** [comment]
CHelper works pretty well.

**Comment by lazyboson** [comment]
it is now working on code chef with competitive companion, post modification of custom port. you can close it.

**Comment by slycelote** [comment]
This will be fixed in the next release.
