### ISSUE TITLE
Cannot parse double-char

### ISSUE THREAD

**Issue by vpyvovar** [slycelote/caide#30]
The issue started behaving differently, but have not been fully fixed.
(Sorry, i dont know how to re-activate this:
https://github.com/slycelote/caide/issues/29)

Image of issue:
Contest had E1 and E2
https://pasteboard.co/Jfg2DOh.png

https://codeforces.com/contest/1374

**Comment by slycelote** [comment]
Which build are you using? I haven't published the new version of the extension yet, unfortunately.

**Comment by slycelote** [comment]
I published a [new release](https://github.com/slycelote/caide/releases/tag/v2.5.0) on Github that should resolve this. Will upload it to VS marketplace in a few days; in the meantime you can download the VSIX from the release page and install manually.
