### ISSUE TITLE
Display running time per test in the report

### ISSUE THREAD

**Issue by Spidy104** [slycelote/caide#32]
Sorry to disturb/interrupt your beautiful work on caide, but I wanted to say something.
While running the tests, can you do something so as it shows the running time of our code, it helps us understand better  the efficiency of our solution
Sorry for the poor English, since it is not my native language.
Thanks...
Happy Coding...

**Comment by Spidy104** [comment]
I also had one more question about what should be the port in the extension so that competitive companion can interact with caide

**Comment by slycelote** [comment]
The default port, as described [here](https://github.com/slycelote/caide/tree/master/libcaide) is 10043; you can also change it via `companion_port` setting.
As for running time per test, I agree that it is a good idea.

**Comment by Spidy104** [comment]
Okay thanks and the And pls look into the matter of the running time as it would be helpful
