### ISSUE TITLE
Code analysis errors

### ISSUE THREAD

**Issue by Spidy104** [slycelote/caide#33]
1>LINK : fatal error LNK1104: cannot open file 'D:\cp\cpp\CAIDESLN\cpplib\Debug\cpplib.lib'
1>Done building project "AWatermelon.vcxproj" -- FAILED.
THIS IS AN error I am continuously getting, how to fix this.

**Comment by slycelote** [comment]
There is a problem when the solution has just been created in Visual Studio. As a workaround, close VS and reopen the solution.

**Comment by Spidy104** [comment]
Okay, thanks I reopened but it did not work instead, I ran code analysis on the solution.

**Comment by slycelote** [comment]
Can you clarify what exactly you're doing?
If you build the project normally in VS, are there any errors?

**Comment by Spidy104** [comment]
Just the normal things ctl-f7 for compiling and f5 for debugging, while running the tests I got that.

**Comment by slycelote** [comment]
Please describe exactly what the problem is.
Paste all error messages here, attach screenshots etc etc.

**Comment by Spidy104** [comment]
I said it already man, look above 
1>LINK : fatal error LNK1104: cannot open file 'D:\cp\cpp\CAIDESLN\cpplib\Debug\cpplib.lib'
1>Done building project "AWatermelon.vcxproj" -- FAILED.
Here is the error again, but currently it is fixed.

**Comment by slycelote** [comment]
I see, from this message I wrongly assumed that when you press the "run tests" button the code analysis is running instead.

> but it did not work instead, I ran code analysis on the solution.
