### ISSUE TITLE
How to include prewritten code library?

### ISSUE THREAD

**Issue by slycelote** [slycelote/caide#35]
I also had a question, what is I want to include some pre-written library of mine in my solution, but it is not present in the cpplib folder, How shall we do that?

_Originally posted by @Spidy104 in https://github.com/slycelote/caide/issues/34#issuecomment-735075317_

**Comment by slycelote** [comment]
You copy the library into the cpplib directory.

**Comment by Spidy104** [comment]
Okay, then can it include from outside?

**Comment by Spidy104** [comment]
Like as in the caide.ini file I'll just write "-I /path/to/library"

**Comment by slycelote** [comment]
I think this may work as long as your library is header-only. The headers won't appear in VS solution though.
Better replace cpplib directory with a symlink to your external folder.

**Comment by Spidy104** [comment]
Okay thanks

**Comment by Spidy104** [comment]
I had a question if I wanted to include the boost library what should be done, and also in the cpplib directory if I create sub directories, then would caide be able to include them in my solution and in my submission.cpp file.

**Comment by slycelote** [comment]
You probably won't be able to use boost, because that library is too complicated. Subdirectories should be fine, you can try and open an issue if it doesn't work.
