### ISSUE TITLE
Visual Studio not responding when loading the caide solution

### ISSUE THREAD

**Issue by Spidy104** [slycelote/caide#37]
While loading the solution, Visual Studio stops responding, after 2 or 3 times of manual opening or closing it works.

**Comment by slycelote** [comment]
Can you share your solution folder, and screenshots of hanging VS and About window?
Do you have other extensions installed?
Do you open with double click or via the main menu?
Can you reproduce the issue with all extensions disabled?

**Comment by Spidy104** [comment]
I had uninstalled visual studio and reinstalled it and it has not happened yet, if it happens then I will share it. Till then I am closing this issue.
