### ISSUE TITLE
Including Prewritten Headers

### ISSUE THREAD

**Issue by Spidy104** [slycelote/caide#38]
In the readme, it was told to put all my pre-written headers in the cpplib directory.
What if we put the whole directory in the cpplib directory so will it be able to parse the other headers as I have something like this ... 
numbers/
                                      /...Headers
Graphs/
                                     /...Headers

**Comment by slycelote** [comment]
Yes, it will work as long as you set up include paths correctly in caide.ini

**Comment by Spidy104** [comment]
Then Copy Pasting the files into the cpplib directory would not be required?

What if the place where my prewritten code is present in other subdirectories in a particular directory, then including that particular directory which contains all my subdirectories then would it be able to parse them.

**Comment by slycelote** [comment]
Headers may be in any directory. cpp files must be in cpplib.

**Comment by Spidy104** [comment]
my prewritten code are all present in header files nothing in *.cpp files everything is present in *.cpp. And only for the headers I have to include the paths in the caide.ini only?

**Comment by slycelote** [comment]
Visual Studio by default will only add cpplib as include directory. You'll have to add other include directories in vs_common.props.

**Comment by Spidy104** [comment]
Ok Thanks, then what If I copy paste all those directories in the cpplib directory.

**Comment by slycelote** [comment]
It will work. Instead of copying you can also use [directory symlinks](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink).

**Comment by Spidy104** [comment]
Thanks for me with and sorry for those useless questions, till an another error comes I am closing this issue
