### ISSUE TITLE
Use gcc in command line caide in windows

### ISSUE THREAD

**Issue by Spidy104** [slycelote/caide#40]
Can we use gcc for windows in caide command line UI??

**Comment by slycelote** [comment]
Caide itself doesn't call any compiler. It can optionally use header files installed with a compiler for parsing the source code, if you use any compiler-specific extensions, but that's probably not what you need (the bundled MinGW headers should always be sufficient).
If you want to compile from command line, use regular commands like `g++ problemA.cpp problemA_test.cpp`.
