### ISSUE TITLE
Caide should not remove constructor from TopCoder solution

### ISSUE THREAD

**Issue by Dlougach** [slycelote/caide#45]
I tend to have put some precalculations into the constructor for TopCoder solutions. Unfortunately, I found out the hard way that without "caide keep" comment it simply removes that constructor. I suggest 2 options:

1) Make it possible to configure the topcoder template in such way that it always adds default constructor with the "keep" comment.
2) Somehow magically figure out that in topcoder that constructor will be called. While we are at it maybe the same can be done with the main method.

**Comment by slycelote** [comment]
All fair points. Right now, part of solution code for TopCoder is generated by hardcoded logic inside caide.
* As an immediate solution, I can modify that logic to always add a constructor with `// caide keep`. Will that work for you?
* More generally, I have some preliminary implementation that allows more flexible configuration of generated code (based on [Mustache templates](https://mustache.github.io/)). So the hardcoded logic will move to user-defined template.
* Doing this automagically, without relying on `// caide keep` comments, is also possible and has been on my TODO forever. But workarounds are easy enough, so I never bothered...

**Comment by Dlougach** [comment]
- constructor with keep will certainly work for now
- alternative - just keep solve() for now. Or introduce a new tag - "keepdeps". It would not protect the function from removal but will protect all its dependencies. Then this keepdeps can be attached to solve()

**Comment by slycelote** [comment]
> 2\. Somehow magically figure out that in topcoder that constructor will be called. While we are at it maybe the same can be done with the main method.

This will be included in the next release.
