### ISSUE TITLE
How to modify the automatically generated code template

### ISSUE THREAD

**Issue by KargathEx** [slycelote/caide#51]
The automatically generated *.cpp files do not contain some necessary header files, so I have to add `#include<cctype>` every time to use `std::isupper`,
Is there a way to modify the generated template？   
Where should I modify?

**Comment by slycelote** [comment]
In `templates` directory

**Comment by KargathEx** [comment]
I am using a plugin for visual studio 2022, can you please indicate the full path to the `template`?

**Comment by slycelote** [comment]
In the directory of your Visual Studio solution.
