### ISSUE TITLE
std::to_string cannot be used due to weird mingw 4.8 headers.

### ISSUE THREAD

**Issue by Predelnik** [slycelote/caide#9]
Using `std::to_string` leads to failed clang parsing.

I couldn't really figure out what is valid fix or workaround for this. Seems like defining `_GLIBCXX_USE_C99` should help but then it results in bunch of other errors. Maybe just updating headers would help but I don't know how hard it is exactly.

**Comment by slycelote** [comment]
Yes, it's a bug in an older version of MinGW. I need to update it. If you download newer MinGW headers and replace corresponding `-isystem` paths in caide.ini, everything should work.

Alternatively, you can try using your system's headers instead. For example, in 64-bit Linux I use clang options `-itarget x86_64-linux -isystem caide/include`. You may need to add some of your system search paths manually, their list can be seen in the output of `g++ -x c++ -c -v /dev/null -o /dev/null`.

**Comment by Predelnik** [comment]
Ok I actually use VsCaide so no system headers for me. I'll probably try to download mingw and replace headers.

**Comment by Predelnik** [comment]
Upgrade to mingw-w64 gcc 4.9.3 headers worked nicely and `std::to_string` works.

You may close this issue or keep it if you plan to upgrade headers in the future version. Thanks!

**Comment by slycelote** [comment]
Updated bundled libstdc++ headers to version 6.3, so this is fixed.
